#!/usr/bin/env bash

source ./modules/common.sh

source ./modules/000-envs.sh
source ./modules/001-uefi.sh
source ./modules/002-config.sh
source ./modules/003-network.sh
source ./modules/004-filesystem.sh
source ./modules/005-pacstrap.sh
source ./modules/009-chroot.sh

