#!/usr/bin/env bash
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
MODE="${1:-PREINSTALL}"

case "${MODE,,}" in 
  preinstall)
    MODULE_PATH="000-preinstall" ;;

  install)
    MODULE_PATH="001-install" ;;

  postinstall)
    MODULE_PATH="002-postinstall" ;;

  *)
    die "Invalid mode '$MODE'!" ;;
esac

source "$SCRIPT_DIR/require.sh" io modules

run-modules "$SCRIPT_DIR/modules/$MODULE_PATH"

exit 0



if [[ "$MODE" == "PREINSTALL" ]]; then
  info "In mode '$MODE'."

  for f in $SCRIPT_DIR/modules/000-preinstall; do
      [[ -e "$f" ]] || continue
      echo "$f"
      source "$f"
  done

elif [[ "$MODE" == "CHROOT" ]]; then
  info "In mode '$MODE'."

  source "$SCRIPT_DIR/install_config.env"

  for f in $SCRIPT_DIR/modules/1*.sh; do
      [[ -e "$f" ]] || continue
      echo "$f"
      source "$f"
  done

elif [[ "$MODE" == "POSTINSTALL" ]]; then
  info "IN $MODE"
else
  die "Mode '$MODE' not recognized!"
fi

