#!/usr/bin/env bash
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
MODE="${1:-PREINSTALL}"

source "$SCRIPT_DIR/modules/common.sh"
source "$SCRIPT_DIR/modules/defaults.sh"

if [[ "$MODE" == "PREINSTALL" ]]; then
  info "In mode '$MODE'."

  for f in $SCRIPT_DIR/modules/00*.sh; do
      [[ -e "$f" ]] || continue
      echo "$f"
      source "$f"
  done

elif [[ "$MODE" == "CHROOT" ]]; then
  info "In mode '$MODE'."

  for f in $SCRIPT_DIR/modules/01*.sh; do
      [[ -e "$f" ]] || continue
      echo "$f"
      source "$f"
  done

elif [[ "$MODE" == "POSTINSTALL" ]]; then
  info "IN $MODE"
else
  die "Mode '$MODE' not recognized!"
fi

